storage: /verdaccio/storage
max_body_size: 500mb
uplinks:
  npmjs:
    url: https://registry.npmjs.org/

log: { type: stdout, format: pretty, level: error }

auth:
  htpasswd:
    file: ./htpasswd

packages:
  '@*/*':
    access: $all
    publish: $all
    proxy: npmjs
  '**':
    access: $all
    publish: $all
    proxy: npmjs
